spring:
  application:
    name: carcar


  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

  profiles:
    active: dev

  jackson:
    date-format: YYYY-MM-DD
    joda-date-time-format: YYYY-MM-DD HH:mm:ss

mybatis:
  mapper-locations: classpath:sqlmapper/*.xml
  type-aliases-package: com.jeff.carcar.entity
  check-config-location: true
  config-location: classpath:mybatis.xml

logging:
  config: classpath:logback.xml

server:
  port: 8082
  session:
    timeout: 1800
  connection-timeout:  60000
  display-name: Boot Application
  context-path: /carcar

---
spring:
   profiles: dev
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     url: jdbc:mysql://10.8.27.5:3306/db_draw?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true
     password: 123456
     type:  com.alibaba.druid.pool.DruidDataSource
     druid:
       filters: config
       maxActive: 50
       initialSize: 10
       maxWait: 60000
       minIdle: 1
       timeBetweenEvictionRunsMillis: 60000
       minEvictableIdleTimeMillis: 300000
       validationQuery: select 'x'
       testWhileIdle: true
       testOnBorrow: false
       testOnReturn: false
